{{- if .Values.worker.keda.enabled -}}
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: {{ include "event-platform.componentName" (dict "root" . "component" "rabbitmq") }}
  labels:
    {{- include "event-platform.labels" . | nindent 4 }}
spec:
  secretTargetRef:
    - parameter: host
      name: {{ include "event-platform.secretName" . }}
      key: RABBITMQ_URL
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include "event-platform.componentName" (dict "root" . "component" "worker") }}
  labels:
    {{- include "event-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "event-platform.componentName" (dict "root" . "component" "worker") }}
  pollingInterval: {{ .Values.worker.keda.pollingInterval }}
  cooldownPeriod: {{ .Values.worker.keda.cooldownPeriod }}
  {{- if hasKey .Values.worker.keda "idleReplicaCount" }}
  idleReplicaCount: {{ .Values.worker.keda.idleReplicaCount }}
  {{- end }}
  minReplicaCount: {{ .Values.worker.keda.minReplicaCount }}
  maxReplicaCount: {{ .Values.worker.keda.maxReplicaCount }}
  {{- if .Values.worker.keda.fallback.enabled }}
  fallback:
    failureThreshold: {{ .Values.worker.keda.fallback.failureThreshold }}
    replicas: {{ .Values.worker.keda.fallback.replicas }}
  {{- end }}
  advanced:
    restoreToOriginalReplicaCount: false
    {{- with .Values.worker.keda.hpaBehavior }}
    horizontalPodAutoscalerConfig:
      behavior:
        {{- toYaml . | nindent 8 }}
    {{- end }}
  triggers:
    - type: rabbitmq
      metadata:
        protocol: amqp
        queueName: {{ .Values.queue.name | quote }}
        mode: QueueLength
        value: {{ .Values.worker.keda.queueLength | quote }}
        activationValue: {{ .Values.worker.keda.activationValue | quote }}
      authenticationRef:
        name: {{ include "event-platform.componentName" (dict "root" . "component" "rabbitmq") }}
{{- end }}
