{{- if .Values.secrets.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "event-platform.secretName" . }}
  labels:
    {{- include "event-platform.labels" . | nindent 4 }}
type: Opaque
stringData:
  RABBITMQ_URL: {{ include "event-platform.rabbitmqUrl" . | quote }}
{{- end }}
