apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: event-platform
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: event-platform
  source:
    repoURL: https://github.com/your-org/keda-event-platform.git
    targetRevision: main
    path: deploy/helm/event-platform
    helm:
      valueFiles:
        - ../../environments/prod/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: event-platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
